pipeline {
    agent any

    stages {
        stage('Unit Tests - Backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                    alwaysPull true
                }
            }

            steps {
                dir('bugtracker-backend') {
                    sh '''
                export GOCACHE="$PWD/.cache"
                mkdir -p "$GOCACHE"
                go build -o bugtracker-backend cmd/bugtracker/main.go

                go test -v ./... 2>&1 | go-junit-report -set-exit-code > report.xml

                # Generate coverage report
                go test -coverprofile=coverage.out -covermode=atomic ./...
                go tool cover -html=coverage.out -o coverage.html

                mkdir -p reports
                mv coverage.html reports/
                mv report.xml reports/
                '''
                }
            }
            post {
                always {
                    junit 'bugtracker-backend/reports/report.xml'
                    publishHTML target: [
                        allowMissing: true,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'bugtracker-backend/reports',
                        reportFiles: 'coverage.html',
                        reportName: 'Backend Coverage Report'
                    ]
                }
            }
        }
    }
}
